### ISSUE TITLE
cpdz problem for version.6.1.8

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#225] opened 2023-10-28 04:27 UTC
Indoubtedly, the cpdz pack is a milestone for Calcpad.

It functions well.However, everytime I run the calculation, the images included will be copied and placed under the drive where the cpdz is located.

**Comment by Proektsoftbg** [comment] 2023-10-28 18:05
Hi! Thank you!

The images are extracted when you open the file, not when you run the calculations. This is necessary, because they are referenced in the html code as `<img>` tags. So, they need to be there for the browser engine to find and show them also in the input form. This is how it works.

So, this is not a bug, it is expected. We can make Calcpad to delete images after closing the file to save space, but they are usually too small to make any problems. You can better organize the images by placing them in subfolders, like '`./Images/`'. In this way, they will not mess up with your cpdz files.

The other option is to embed the images in the html by converting them to Base64 and rewriting the respective contents of the src references. Then, we will not have any image files copied. However, embedding larger images in Html as Base64 strings is not recommended. This approach has many issues and I use it only for very small images like icons.

**Comment by idealkindom** [comment] 2023-10-29 03:13
Hi,Ned. If Calcpad could manipute files, then Calcpad could be set default to add a string of command when packing a cpdz file, so as to delete the referred files such as images after the calculation.


Another problem is that if a cpdz file includes some images, then when it is #include by another cpd or cpdz file, the images will not show up.
















At 2023-10-29 02:05:16, "Ned Ganchovski" ***@***.***> wrote:

Hi! Thank you!

The images are extracted when you open the file, not when you run the calculations. This is necessary, because they are referenced in the html code as <img> tags. So, they need to be there for the browser engine to find and show them also in the input form. This is how it works.

So, this is not a bug, it is expected. We can make Calcpad to delete images after closing the file to save space, but they are usually too small to make any problems. You can better organize the images by placing them in subfolders, like './Images/'. In this way, they will not mess up with your cpdz files.

The other option is to embed the images in the html by converting them to Base64 and rewriting the respective contents of the src references. Then, we will not have any image files copied. However, embedding larger images in Html as Base64 strings is not recommended. This approach has many issues and I use it only for very small images like icons.

**Comment by Proektsoftbg** [comment] 2023-10-29 09:41
If we delete the pictures after calculations, they will not be visible in the output. They are only referenced in the Html, not embedded in the code. We can do some cleanup after you close the file, but this can still cause problems. If you saved a hardcopy of the results as an Html or docx file, you will not see the images there too.

I do not think that is it is a big trouble to have a folder "./Images" next to your file. Calcpad is based on Html and this is how Html works. Packing the images into cpdz files makes the distribution of cpdz files easier. You do not need to send or copy a bunch of files with it each time. After you place your file at certain location and open it, the file structure is restored at the new location.

**Closed by Proektsoftbg** 2023-10-29 09:41 UTC
