### ISSUE TITLE
About selection of html

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#38] opened 2022-08-12 08:55 UTC
1. I tried a html coding Group selection list in web browser and it works fine, while it errors in Calcpad. So how could I realise the Group selection list in Calcpad.

2. Maybe there is a need for structural engineer, i.e. input some patameters in the prosess of calculation, because judgements should be made according to some trial calculation. Whether it is possible in Calcpad worksheet?
3. Inputing a greek letter with a Latin letter plus Ctrl+G is not so efficient, how about Esc plus a Latin letter, or a Latin letter plus Tab?
4. I found ＜= and ＞= are not recognizable in Calcpad. I think using mouse to click and input logical symbols is not so convenient.

**Comment by cser** [comment] 2022-08-12 09:35
> 2. Maybe there is a need for structural engineer, i.e. input some patameters in the prosess of calculation, because judgements should be made according to some trial calculation. Whether it is possible in Calcpad worksheet?

+1
But there are problems with back compability and other.

> 3. Inputing a greek letter with a Latin letter plus Ctrl+G is not so efficient, how about Esc plus a Latin letter, or a Latin letter plus Tab?

It's unlikely that the operating system allows shortcuts like <kbd>Esc</kbd>+<kbd>Letter</kbd>.
And how to separate Letter/Tab inserting from <kbd>Tab</kbd>+<kbd>Letter</kbd> shortcut?
But you can experiment with Clavier++ and Beeftext to try to find shortcuts better then <kbd>Letter</kbd>, <kbd>Ctrl</kbd>+<kbd>G</kbd>.
Enother alternative is to install greek keyboard layout.

> 4. I found ＜= and ＞= are not recognizable in Calcpad. I think using mouse to click and input logical symbols is not so convenient.

I can't find shortcuts for it too and use Beeftext with shortcuts <=++, >=++.
2 @Proektsoftbg - is this shortcuts exists?

**Comment by Proektsoftbg** [comment] 2022-08-12 22:48
1. Can you please share the source of what you are trying to do and what errors do you get? Meybe we can figure out something.
2. Sorry, cannot fully understand what is needed.
3. Ctrl + G is the same as MathCAD. 
4.  Even if＜= and ＞= are not supported, we can include them as shortucts. If you type these sequences, the editor will replace them with ≤ and ≥, respectively. What about that?

**Comment by cser** [comment] 2022-08-13 05:42
4 - html has not sequeses like <= or =>. So, no problem to convert it to ≤ and ≥ on input

**Comment by hildebrandopsj** [comment] 2022-08-13 16:16
@Proektsoftbg i think the item 2 of @idealkindom is:

Example:
In a pile cap, the steel reinforcement is determined after we have defined the geometry and angle of struts, but we need to do some trial and error to encounter the correct values.

Today, in calcpad we have two option's (maybe more):
1. Leave the post input's equal zero (The reinforcement area) until we analyze the result's, with results in hand, we can run the script again including the missing parameters.
2. Using a second script just to determine the reinforcement area.

Maybe a new output visibility control with a similar behaviour to a break point.

Example:
#section(1)
Some function and input values to define the strut angles and verify the tension
#end section(1)

#section(2)
Some function and input values to define the reinforcement
#end section(2)

When we run the script using (F4), calcpad show the input values of the #section(1). 

Pressing (F5) to run, calcpad show the results of #section(1). The user analyze this result's and choose to   run #section(1) again, or go to #section(2).

After run all sections, calcpad show the complete results to export.

I dont know if this can be achievieng using #macros, i still need to study this. If this is possible, sorry for this long answer.

Best regards

**Comment by hildebrandopsj** [comment] 2022-08-13 16:26
> 1. Can you please share the source of what you are trying to do and what errors do you get? Meybe we can figure out something.
> 2. Sorry, cannot fully understand what is needed.
> 3. Ctrl + G is the same as MathCAD.
> 4. Even if＜= and ＞= are not supported, we can include them as shortucts. If you type these sequences, the editor will replace them with ≤ and ≥, respectively. What about that?

3. Is the same in smath studio.
4. This would be great!

**Comment by idealkindom** [comment] 2022-08-14 01:16
> @Proektsoftbg i think the item 2 of @idealkindom is:
> 
> Example: In a pile cap, the steel reinforcement is determined after we have defined the geometry and angle of struts, but we need to do some trial and error to encounter the correct values.
> 
> Today, in calcpad we have two option's (maybe more):
> 
> 1. Leave the post input's equal zero (The reinforcement area) until we analyze the result's, with results in hand, we can run the script again including the missing parameters.
> 2. Using a second script just to determine the reinforcement area.
> 
> Maybe a new output visibility control with a similar behaviour to a break point.
> 
> Example: #section(1) Some function and input values to define the strut angles and verify the tension #end section(1)
> 
> #section(2) Some function and input values to define the reinforcement #end section(2)
> 
> When we run the script using (F4), calcpad show the input values of the #section(1).
> 
> Pressing (F5) to run, calcpad show the results of #section(1). The user analyze this result's and choose to run #section(1) again, or go to #section(2).
> 
> After run all sections, calcpad show the complete results to export.
> 
> I dont know if this can be achievieng using #macros, i still need to study this. If this is possible, sorry for this long answer.
> 
> Best regards

Absoulutely is what I want to say.Some parameter can not decided and be input at the begining, breaks are need and new prompt input brackets are need in the calculation process.

**Comment by idealkindom** [comment] 2022-08-14 01:51
> 1. Can you please share the source of what you are trying to do and what errors do you get? Meybe we can figure out something.
> 2. Sorry, cannot fully understand what is needed.
> 3. Ctrl + G is the same as MathCAD.
> 4. Even if＜= and ＞= are not supported, we can include them as shortucts. If you type these sequences, the editor will replace them with ≤ and ≥, respectively. What about that?

> 1. Can you please share the source of what you are trying to do and what errors do you get? Meybe we can figure out something.
> 2. Sorry, cannot fully understand what is needed.
> 3. Ctrl + G is the same as MathCAD.
> 4. Even if＜= and ＞= are not supported, we can include them as shortucts. If you type these sequences, the editor will replace them with ≤ and ≥, respectively. What about that?

2.the code in html fies:
<select name="car">
    <optgroup label="Chinese Car">
        <option value="HQ">Red Flag</option>
        <option value="BYD">BYD</option>
        <option value="QR">Cherry</option>
    </optgroup>
 
    <optgroup label="German Car">
        <option value="BZ">BMW</option>
        <option value="VK">Volkswagon</option>
    </optgroup>
    <optgroup label="Janpanese Cherry" disabled>
        <option value="HD" selected>Honda</option>
        <option value="TY">Toyota</option>
        </optgroup>
</select>

and the results in web browser can be easily checked.

The codes in comments.for Calcpad should be like:

 '<selectname ="car">
          '<optgrouplabel = "Chinese Car"> 
               '<optionvalue = "HQ"> RedFlag </option > 
                '<optionvalue ="BYD">BYD</option > 
               '<optionvalue ="QR">Cherry </option > 
                    '</optgroup > 
                     '<optgrouplabel = "German Car"> 
                  '<optionvalue = "BZ"> BMW </option > 
                   '<optionvalue ="VK">Volkswagon</option > 
                   '</optgroup> 
                '<optgrouplabel="Janpanese Cherry"disabled > 
               '<optionvalue="HD"selected>Honda</option> 
                '<optionvalue="TY">Toyota </option> 
                  '</optgroup> 
               '</select> 

Calcpad does not errors but the outcome is not expected.
2.See What Hild said, that's what I want to convey.Some calculation you can not inout all the parameter values at the begining, you need some preparation calculation to help you to judge and guess a close parameter vaule and continue the calculation and observe and retry, for which breaks and prompt input boxes would be a very good choice.

3.I never used MathCad, instead I used wxMaxima and TeXmacs a lot. The former one use Esc+ keyboard to call a selection box to input greek letters and some logical operators, the latter, maybe use a more convenient way, just keyboards+Tab. Both of them are quite efficient.Ctrl+G  could be accustomed, of course.

4.That's a good idea to add ＜= to be recognized as ≤ and the counterpart reverse. I advise to add == also for the logical = with 3 lines.

**Comment by Proektsoftbg** [comment] 2022-08-14 17:56
Hi,

Please, do not put so many different things in one issue. It is better to have a separate issue for each separate thing. It will be easier to read and discuss.

1. Calcpad has native support only for input (text) fields, generated by the question marks "`?`". Everything else is not parsed by Calcpad but simply sent to the output as is. For Calcpad it is just comments. It works because the output is Html and it is rendered in a web browser control.

So, in order to have any other Html UI elements working in Calcpad, they must be bound to some question marks "`?`". It is done by assigning `data-target="tgt"` that matches the id of some container element, e.g. `'<p id="tgt">' x = ?'</p>`
Please, checj the following discussion about UI elements: [https://github.com/Proektsoftbg/Calcpad/discussions/30](https://github.com/Proektsoftbg/Calcpad/discussions/30)

Since Calcpad supports only numeric values as input, only numbers can be placed in the "value" attribute. So, the correct code is:

```
'Select a car - <select name="car" data-target="car">
'<optgroup label = "Chinese Car">
'<option value="1">RedFlag</option>
'<option value="2">BYD</option>
'<option value="3">Cherry</option>
'</optgroup>
'<optgroup label="German Car">
'<option value="4"> BMW</option>
'<option value="5">Volkswagon</option>
'</optgroup>
'<optgroup label="Janpanese Cherry" disabled>
'<option value="6">Honda</option>
'<option value="7">Toyota</option>
'</optgroup>
'</select>
'<p id="car"> Values:'id = ? '</p>
```
You can try it, it works, but you have to compile the code to a web form with the left one button.
![image](https://user-images.githubusercontent.com/90918363/184548902-4ef6cc08-1f93-46c6-aee0-9524cbac08b4.png)
Then, when you run the solution, you will get:
![image](https://user-images.githubusercontent.com/90918363/184548920-7a761852-bc48-423c-879c-44e661dc1be3.png)

**Comment by Proektsoftbg** [comment] 2022-08-14 18:16
2. Thank you @hildebrandopsj. Now I see. What I do in such cases now is very simple: 
2.1. Put some initial values for all parameters.
2.2. Run the calculations.
2.3. See the results.
2.4. Go back to input and change what I need.
Sometimes, I may want to change not the reinforcement area, but section depth or concrete/steel grade or other factor that matters.

However, we can consider some step-by-step solution that pauses for user input. 
But instead of `#section` - `#end secton`, we can simply put `#pause`. It will run the code until it reaches `#pause`, render the results to that line and display the rest as an input form (to the next `#pause`).

It will aslo allow for what @cser requested - to display one or other input, depending on some intermediate value. Now, it will be possible, because the value in the `#if` check will be calculated at the previous stage.

If you agree with this, I will include it to the wish list, but after vectors and matrices.

**Comment by Proektsoftbg** [comment] 2022-08-14 18:21
3. We have already implemented at as Ctrl+G and it is not good to change shortcuts, because existing users will get confused. Also, it is not good to have many shortcuts for one and the same thing. So, we will leave it Ctrl+G for now, it is not a big issue. What we can do in future is to allow users to customize shortcuts. In this way, everyone can set whatever shorcut he/she likes. :)

If you agree with this solution, I will add it to the wishlist.

**Comment by Proektsoftbg** [comment] 2022-08-14 18:27
4. OK, I will add <=, >= and == as shortcuts for the respective symbols. This is a very good idea. They will be simply rewritten during typing / syntax highlithing. So, it is not required to change the language parser. I can do it very quick and easy and will post an update the next few days. :)

**Comment by Proektsoftbg** [comment] 2022-08-14 18:28
4. OK, I will add <=, >= and == as shortcuts for the respective symbols. This is a very good idea. They will be simply rewritten during typing / syntax highlithing. So, it is not required to change the language parser. I can do it very quick and easy and will post an update the next few days. :)

**Comment by idealkindom** [comment] 2022-08-15 02:29
> 4. OK, I will add <=, >= and == as shortcuts for the respective symbols. This is a very good idea. They will be simply rewritten during typing / syntax highlithing. So, it is not required to change the language parser. I can do it very quick and easy and will post an update the next few days. :)

That's great.

**Comment by idealkindom** [comment] 2022-08-15 02:30
> 3. We have already implemented at as Ctrl+G and it is not good to change shortcuts, because existing users will get confused. Also, it is not good to have many shortcuts for one and the same thing. So, we will leave it Ctrl+G for now, it is not a big issue. What we can do in future is to allow users to customize shortcuts. In this way, everyone can set whatever shorcut he/she likes. :)
> 
> If you agree with this solution, I will add it to the wishlist.

Yes, alowing the user to set shorcuts would be a more versatile answer .

**Comment by idealkindom** [comment] 2022-08-15 04:00
> 

Thanks a lot,Ned.I copied your code but I found Calcpad is so space sensitive. I checked word by word, symbol ny symbol, finally made it. Still it' quite not so intuitive and easy to do.

**Comment by Proektsoftbg** [comment] 2022-08-15 08:07
@idealkindom Maybe the problem is that we recently made the "select" element to be automatically replaced by the selected content in the `#post` stage. Please check the discussion:

[https://github.com/Proektsoftbg/Calcpad/discussions/25#discussioncomment-3127629](https://github.com/Proektsoftbg/Calcpad/discussions/25#discussioncomment-3127629)

This is good in general but it does not allow you to see the immediate result while coding. Thanks to your feedback, I can realize now, that in this way, we made more dificult to program the Html element. So, we can make this replacement to happen only if you add `class="post"`.

Yes, I agree that these things are difficult now, but after we recently introduced macros, it will be much more easier. We can create a library with macro helpers for all useful Html elements. Please, check this discussion:

[https://github.com/Proektsoftbg/Calcpad/discussions/33#discussioncomment-3348527](https://github.com/Proektsoftbg/Calcpad/discussions/33#discussioncomment-3348527)

**Comment by idealkindom** [comment] 2022-08-15 10:28
> @idealkindom Maybe the problem is that we recently made the "select" element to be automatically replaced by the selected content in the `#post` stage. Please check the discussion:
> 
> [#25 (comment)](https://github.com/Proektsoftbg/Calcpad/discussions/25#discussioncomment-3127629)
> 
> This is good in general but it does not allow you to see the immediate result while coding. Thanks to your feedback, I can realize now, that in this way, we made more dificult to program Html elements. So, we can make this replacement to happen only if you add `class="post"`.
> 
> Yes, I agree that these things are difficult now, but after we recently introduced macros, it will be much more easier. We can create a library with macro helpers for all useful Html elements. Please, check this discussion:
> 
> [#33 (reply in thread)](https://github.com/Proektsoftbg/Calcpad/discussions/33#discussioncomment-3348527)

Thanks a lot,Ned.I imagine the tool→insert→html could add more function, and if Calcpad could add a switch to hide and show the codes about html elements gloabally with one click when writing math codes, it would help the user concentrate more on the logics and calculations.

**Comment by hildebrandopsj** [comment] 2022-08-15 11:40
> 2. Thank you @hildebrandopsj. Now I see. What I do in such cases now is very simple:
>    2.1. Put some initial values for all parameters.
>    2.2. Run the calculations.
>    2.3. See the results.
>    2.4. Go back to input and change what I need.
>    Sometimes, I may want to change not the reinforcement area, but section depth or concrete/steel grade or other factor that matters.
> 
> However, we can consider some step-by-step solution that pauses for user input. But instead of `#section` - `#end secton`, we can simply put `#pause`. It will run the code until it reaches `#pause`, render the results to that line and display the rest as an input form (to the next `#pause`).
> 
> It will aslo allow for what @cser requested - to display one or other input, depending on some intermediate value. Now, it will be possible, because the value in the `#if` check will be calculated at the previous stage.
> 
> If you agree with this, I will include it to the wish list, but after vectors and matrices.

That be amazing! Thank you so much!

Off course, there is no problem to do after vetors and matrices, it's the only thing that keep me apart from leaving completily Smath Studio.

Best regards!

**Comment by idealkindom** [comment] 2022-08-21 09:36
> 3. We have already implemented at as Ctrl+G and it is not good to change shortcuts, because existing users will get confused. Also, it is not good to have many shortcuts for one and the same thing. So, we will leave it Ctrl+G for now, it is not a big issue. What we can do in future is to allow users to customize shortcuts. In this way, everyone can set whatever shorcut he/she likes. :)
> 
> If you agree with this solution, I will add it to the wishlist.

Hi,Ned. I propose to add Greek letters into auto completion selective list when you press the mapped key, i.e when you press a,the autocompletion box may appear and the second one might be α,thus making a beginner with no need to remeber the key to input the Greek letters, and direct input with key pressing should be more efficient than clicking the mouse on the platte.

**Comment by idealkindom** [comment] 2022-11-08 10:39
> @idealkindom Maybe the problem is that we recently made the "select" element to be automatically replaced by the selected content in the `#post` stage. Please check the discussion:
> 
> [#25 (comment)](https://github.com/Proektsoftbg/Calcpad/discussions/25#discussioncomment-3127629)
> 
> This is good in general but it does not allow you to see the immediate result while coding. Thanks to your feedback, I can realize now, that in this way, we made more dificult to program Html elements. So, we can make this replacement to happen only if you add `class="post"`.
> 
> Yes, I agree that these things are difficult now, but after we recently introduced macros, it will be much more easier. We can create a library with macro helpers for all useful Html elements. Please, check this discussion:
> 
> [#33 (reply in thread)](https://github.com/Proektsoftbg/Calcpad/discussions/33#discussioncomment-3348527)

Hi,Ned. I found that in recent version of Calcpad, when there is a selection list syntax in the calc sheet, when you press F5 to run it, the selction button looks like a circle with the number "21".Though it does not influence the cplalculation, it looks unnatutral.

**Comment by idealkindom** [comment] 2022-11-12 09:33
> 2. Thank you @hildebrandopsj. Now I see. What I do in such cases now is very simple:
>    2.1. Put some initial values for all parameters.
>    2.2. Run the calculations.
>    2.3. See the results.
>    2.4. Go back to input and change what I need.
>    Sometimes, I may want to change not the reinforcement area, but section depth or concrete/steel grade or other factor that matters.
> 
> However, we can consider some step-by-step solution that pauses for user input. But instead of `#section` - `#end secton`, we can simply put `#pause`. It will run the code until it reaches `#pause`, render the results to that line and display the rest as an input form (to the next `#pause`).
> 
> It will aslo allow for what @cser requested - to display one or other input, depending on some intermediate value. Now, it will be possible, because the value in the `#if` check will be calculated at the previous stage.
> 
> If you agree with this, I will include it to the wish list, but after vectors and matrices.

"2.Maybe there is a need for structural engineer, i.e. input some patameters in the prosess of calculation, because judgements should be made according to some trial calculation. Whether it is possible in Calcpad worksheet?"
On this tip,Ned, I read what you wrote in Calcpad's blog on the advantage of Calcpad over excel, where you mentioned "intermediate checks", that's is famialiar with what I think about, "intermediate input", I hope this could make it more clear.
Recently, I wrote several articles on a very popular app called "Zhihu",introducing and promoting Calcpad for Chinese college students and scholars, hoping to see a rise in user number from China.I found I am the first one to mention Calcpad on "Zhihu" and "Weibo", but I think many students will like it.

**Comment by hildebrandopsj** [comment] 2022-11-12 14:19
That's why i love the internet, we all are from different countries and trying to contribute with this software

**Comment by Proektsoftbg** [comment] 2022-11-12 22:21
@idealkindom It is not exactly what i mean in the block post. In most design codes, we often fall into one or other case, depending on some value. If we take wind load for example, a wall may have one, two or three zones (A, B, C), depending on building dimensions. In shuch cases, Calcpad is capable to show different text and pictures in the output for every case. Please, check the example bellow:

![image](https://user-images.githubusercontent.com/90918363/201496417-3601efb0-abf6-4eb4-b21b-e2d4c9fab90b.png)
It shows the pircture, text and formulas for case 2. This is not what you can do with Excel, MathCAD or many other softwares.

However, step-by-step execution is also need for the **user** to decide what values to input, depending on some previous results. I completely agree that this can be very useful in some cases. BTW I have almost managed to implement it with the `#pause` keyword, but still not ready. I have to solve a few problems yet. So, you can expect this feature to appear very soon :).

And thank you both for promoting Calcpad. Your support gives me faith to go on.

**Comment by idealkindom** [comment] 2022-11-14 00:00
> @idealkindom It is not exactly what i mean in the block post. In most design codes, we often fall into one or other case, depending on some value. If we take wind load for example, a wall may have one, two or three zones (A, B, C), depending on building dimensions. In shuch cases, Calcpad is capable to show different text and pictures in the output for every case. Please, check the example bellow:
> 
> ![image](https://user-images.githubusercontent.com/90918363/201496417-3601efb0-abf6-4eb4-b21b-e2d4c9fab90b.png) It shows the pircture, text and formulas for case 2. This is not what you can do with Excel, MathCAD or many other softwares.
> 
> However, step-by-step execution is also need for the **user** to decide what values to input, depending on some previous results. I completely agree that this can be very useful in some cases. BTW I have almost managed to implement it with the `#pause` keyword, but still not ready. I have to solve a few problems yet. So, you can expect this feature to appear very soon :).
> 
> And thank you both for promoting Calcpad. Your support gives me faith to go on.

Yes,I.got what you meant. Thanks a lot Ned.

**Comment by Proektsoftbg** [comment] 2023-03-11 09:06
I think that all suggested features from 1 to 4 are implemented in one or another of the the recent versions. So, I will close this issue. Thank you so much for your cooperation! :) If any other suggestions arise, you can always open a new issue.

**Closed by Proektsoftbg** 2023-03-11 09:06 UTC
